Repository fac-graduate-programme/Esmee-Fairbairn-Foundation, pull requests merged in 2019-09, with the labels that each got.

#21 Edit file structure and package.json
  client/.gitignore
  client/README.md
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.js
  client/src/assets/.gitkeep
  client/src/components/Button/index.js
  client/src/components/Button/style.css
  client/src/components/PopUp/index.js
  client/src/components/Tab/index.js
  client/src/components/TabBody/index.js
  client/src/index.js
  client/src/pages/Note/index.js
  client/src/pages/Note/style.css
  client/src/pages/Questions/index.js
  client/src/pages/Questions/style.css
  client/src/pages/Tips/index.js
  client/src/pages/Tips/style.css
  client/src/pages/Welcome/index.js
  client/src/pages/Welcome/style.css
  client/src/utils/.gitkeep
  client/yarn.lock
  server/.gitignore
  server/app.js
  server/controller/index.js
  server/index.js
  server/package-lock.json
  server/package.json
  src/app.js
  src/index.js
Labels: Need Review

#36 Welcome page
  client/src/pages/Welcome/index.js
  client/src/pages/Welcome/style.css
Labels: Need Review

#40 Tips page
  client/src/pages/Tips/index.js
  client/src/pages/Tips/style.css
Labels: Need Review

#39 Note page
  client/src/pages/Note/index.js
  client/src/pages/Note/style.css
Labels: Need Review

#32 Creating Tab component
  client/src/components/Tab/index.js
Labels: Need Review

#38 Creating TabBody component
  client/src/components/TabBody/index.js
  client/src/components/TabBody/style.css
Labels: Done

#46 App render
  client/public/index.html
  client/src/App.js
  client/src/assets/.gitkeep
  client/src/assets/title-logo.svg
  client/src/style.css
Labels: Need Review

#54 Move package.json for heroku
  .gitignore
  package-lock.json
  package.json
Labels: Need Review

#57 Adding GET route to get questions from salesforce
  package-lock.json
  package.json
  server/controller/index.js
  server/controller/routes/.gitkeep
  server/controller/routes/getQuestions.js
  server/controller/utils/.gitkeep
  server/controller/utils/splitString.js
  server/db/config/.gitkeep
  server/db/config/connection.js
  server/db/queries/.gitkeep
  server/db/queries/getQuestions.js
  server/test/index.js
  server/test/routes/.gitkeep
  server/test/routes/questions.js
Labels: Done

#64 Loading component
  client/src/components/Loading/index.js
  client/src/components/Loading/style.css
Labels: Done

#59 Adding postAnswers route
  package-lock.json
  package.json
  server/controller/index.js
  server/controller/routes/postAnswers.js
  server/db/queries/postAnswers.js
Labels: Request-Change

#62 Fixes Create PopUp #9
  client/src/App.js
  client/src/components/Button/index.js
  client/src/components/PopUp/index.js
  client/src/components/PopUp/style.css
Labels: Done

#71 Convert App.js into functional component
  client/App.js
  client/src/App.js
Labels: Need Review

#73 use useEffect to get questions from salesforce
  client/src/App.js
Labels: Done

#65 add post request from client side
  client/package-lock.json
  client/package.json
  client/src/components/Button/index.js
  client/src/components/PopUp/index.js
  client/src/pages/Note/index.js
  client/src/pages/Questions/index.js
  client/src/pages/Questions/style.css
Labels: Need Review

#84 remove data attribute because refactor to axios
  server/controller/routes/postAnswers.js
Labels: Need Review

#83 Refactor QuestionsPage
  client/src/components/Review/index.js
  client/src/components/Review/style.css
  client/src/components/TabBody/index.js
  client/src/components/TabBody/style.css
  client/src/components/Textarea/index.js
  client/src/pages/Note/index.js
  client/src/pages/Note/style.css
  client/src/pages/Questions/index.js
  client/src/pages/Questions/style.css
  client/src/style.css
  server/controller/routes/getQuestions.js
  server/db/queries/getQuestions.js
Labels: Need Review

#87 add test/./answer.js
  server/test/routes/answers.js
Labels: Need Review

#88 Create QuizPage
  client/package-lock.json
  client/package.json
  client/src/pages/QuizPage/index.js
  client/src/pages/QuizPage/style.css
Labels: Need Review

#67 Test database
  package.json
  server/db/config/connection.js
  server/db/testDB/build.js
  server/db/testDB/build.sql
  server/db/testDB/setUpDB.js
  server/test/queries/queries.test.js
  server/test/routes/questions.js
Labels: Need Review, enhancement

#75 add popup for if tickbox not clicked on Note page
  client/src/pages/Note/index.js
  client/src/pages/Note/style.css
  client/src/pages/Questions/index.js
Labels: Need Review

#80 Add Google Analytics
  client/src/App.js
  package-lock.json
  package.json
Labels: Need Review

#92 Add Travis
  .travis.yml
  package.json
  server/db/config/connection.js
  server/db/testDB/build.sql
  server/db/testDB/setUpDB.js
  server/test/queries/queries.test.js
  server/test/routes/answers.js
Labels: Need Review

#95 charitybase validation
  client/package-lock.json
  client/package.json
  client/src/components/Charitybase/index.js
  client/src/components/Charitybase/list.js
  client/src/components/Charitybase/style.css
  client/src/pages/QuizPage/index.js
  client/src/pages/QuizPage/style.css
  server/controller/index.js
  server/controller/routes/charitybaseReq.js
Labels: Need Review, Work In Progress

#106 add how to set up local tests to readME
  README.md
Labels: Need Review
